<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Variablen" nsURI="http://www.et.tu-dresden.de/ifa/excel" nsPrefix="ecoreModel">
  <eClassifiers xsi:type="ecore:EClass" name="Variablen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MBTCP" lowerBound="1" upperBound="-1"
        eType="#//MBTCP" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Autor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Anzahl_der_Arbeitsblaetter"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBTCP">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MBTCP_Tabelle0" lowerBound="1"
        upperBound="-1" eType="#//MBTCP_Tabelle0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBTCP_Tabelle0">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Variablenname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Datentyp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Adresse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Kommentar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AccessMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Fractiondigits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
