/**
 *
 * $Id$
 */
package pamtram.metamodel.validation;

import pamtram.metamodel.AttributeValueConstraintType;

/**
 * A sample validator interface for {@link pamtram.metamodel.AttributeValueConstraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValueConstraintValidator {
	boolean validate();

	boolean validateType(AttributeValueConstraintType value);
	boolean validateValue(String value);
}
