/**
 *
 * $Id$
 */
package pamtram.metamodel.validation;

import org.eclipse.emf.ecore.EClass;

import pamtram.metamodel.CardinalityType;

/**
 * A sample validator interface for {@link pamtram.metamodel.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateEClass(EClass value);
	boolean validateCardinality(CardinalityType value);
}
