/**
 *
 * $Id$
 */
package pamtram.metamodel.validation;

import pamtram.metamodel.TargetSectionClass;

/**
 * A sample validator interface for {@link pamtram.metamodel.TargetSectionAttribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TargetSectionAttributeValidator {
	boolean validate();

	boolean validateOwningClass(TargetSectionClass value);
	boolean validateUnique(boolean value);
	boolean validateValue(String value);
}
