/**
 *
 * $Id$
 */
package pamtram.metamodel.validation;

import org.eclipse.emf.common.util.EList;

import pamtram.metamodel.TargetSectionAttribute;
import pamtram.metamodel.TargetSectionClass;
import pamtram.metamodel.TargetSectionReference;

/**
 * A sample validator interface for {@link pamtram.metamodel.TargetSectionClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TargetSectionClassValidator {
	boolean validate();

	boolean validateReferences(EList<TargetSectionReference> value);
	boolean validateAttributes(EList<TargetSectionAttribute> value);
	boolean validateContainer(TargetSectionClass value);
}
