/**
 *
 * $Id$
 */
package pamtram.validation;

import org.eclipse.emf.common.util.EList;

import pamtram.mapping.ValueModifierSet;
import pamtram.mapping.FixedValue;
import pamtram.mapping.Mapping;

/**
 * A sample validator interface for {@link pamtram.MappingModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappingModelValidator {
	boolean validate();

	boolean validateMapping(EList<Mapping> value);
	boolean validateModifierSets(EList<ValueModifierSet> value);
	boolean validateGlobalValues(EList<FixedValue> value);
}
