/*******************************************************************************
 * Copyright (C) 2014-2018 Matthias Freund and others, Institute of Automation, TU Dresden
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
/**
 */
package pamtram.structure.constraint.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IItemStyledLabelProvider;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import pamtram.structure.constraint.util.ConstraintAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The adapters generated by this
 * factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The adapters
 * also support Eclipse property sheets. Note that most of the adapters are shared among multiple instances. <!--
 * begin-user-doc --> <!-- end-user-doc -->
 * 
 * @generated
 */
public class ConstraintItemProviderAdapterFactory extends ConstraintAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public ConstraintItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(IItemStyledLabelProvider.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.structure.constraint.EqualityConstraint} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected EqualityConstraintItemProvider equalityConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.structure.constraint.EqualityConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqualityConstraintAdapter() {
		if (equalityConstraintItemProvider == null) {
			equalityConstraintItemProvider = new EqualityConstraintItemProvider(this);
		}

		return equalityConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.structure.constraint.ChoiceConstraint} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceConstraintItemProvider choiceConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.structure.constraint.ChoiceConstraint}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceConstraintAdapter() {
		if (choiceConstraintItemProvider == null) {
			choiceConstraintItemProvider = new ChoiceConstraintItemProvider(this);
		}

		return choiceConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.structure.constraint.NumericConstraint} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected NumericConstraintItemProvider numericConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.structure.constraint.NumericConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumericConstraintAdapter() {
		if (numericConstraintItemProvider == null) {
			numericConstraintItemProvider = new NumericConstraintItemProvider(this);
		}

		return numericConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.structure.constraint.StringConstraint} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected StringConstraintItemProvider stringConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.structure.constraint.StringConstraint}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringConstraintAdapter() {
		if (stringConstraintItemProvider == null) {
			stringConstraintItemProvider = new StringConstraintItemProvider(this);
		}

		return stringConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.structure.constraint.ValueConstraintSourceElement} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected ValueConstraintSourceElementItemProvider valueConstraintSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.structure.constraint.ValueConstraintSourceElement}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createValueConstraintSourceElementAdapter() {
		if (valueConstraintSourceElementItemProvider == null) {
			valueConstraintSourceElementItemProvider = new ValueConstraintSourceElementItemProvider(this);
		}

		return valueConstraintSourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.structure.constraint.ValueConstraintExternalSourceElement} instances.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected ValueConstraintExternalSourceElementItemProvider valueConstraintExternalSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.structure.constraint.ValueConstraintExternalSourceElement}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createValueConstraintExternalSourceElementAdapter() {
		if (valueConstraintExternalSourceElementItemProvider == null) {
			valueConstraintExternalSourceElementItemProvider = new ValueConstraintExternalSourceElementItemProvider(this);
		}

		return valueConstraintExternalSourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.structure.constraint.ValueConstraintGlobalSourceElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValueConstraintGlobalSourceElementItemProvider valueConstraintGlobalSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.structure.constraint.ValueConstraintGlobalSourceElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValueConstraintGlobalSourceElementAdapter() {
		if (valueConstraintGlobalSourceElementItemProvider == null) {
			valueConstraintGlobalSourceElementItemProvider = new ValueConstraintGlobalSourceElementItemProvider(this);
		}

		return valueConstraintGlobalSourceElementItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (equalityConstraintItemProvider != null) equalityConstraintItemProvider.dispose();
		if (choiceConstraintItemProvider != null) choiceConstraintItemProvider.dispose();
		if (numericConstraintItemProvider != null) numericConstraintItemProvider.dispose();
		if (stringConstraintItemProvider != null) stringConstraintItemProvider.dispose();
		if (valueConstraintSourceElementItemProvider != null) valueConstraintSourceElementItemProvider.dispose();
		if (valueConstraintExternalSourceElementItemProvider != null) valueConstraintExternalSourceElementItemProvider.dispose();
		if (valueConstraintGlobalSourceElementItemProvider != null) valueConstraintGlobalSourceElementItemProvider.dispose();
	}

}
