/**
 *
 * $Id$
 */
package pamtram.transformation.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link pamtram.transformation.TransformationMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransformationMappingValidator {
	boolean validate();

	boolean validateSourceMElement(EObject value);
	boolean validateTargetMElement(EList<EObject> value);
}
