/**
 */
package pamtram.mapping.extended.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IItemStyledLabelProvider;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import pamtram.mapping.extended.util.ExtendedAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * @generated
 */
public class ExtendedItemProviderAdapterFactory extends ExtendedAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement
	 * {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 *
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance. <!-- begin-user-doc --> <!-- end-user-doc
	 * -->
	 *
	 * @generated
	 */
	public ExtendedItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(IItemStyledLabelProvider.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.AttributeMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingItemProvider attributeMappingItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.AttributeMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingAdapter() {
		if (attributeMappingItemProvider == null) {
			attributeMappingItemProvider = new AttributeMappingItemProvider(this);
		}

		return attributeMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.AttributeMappingSourceElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingSourceElementItemProvider attributeMappingSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.AttributeMappingSourceElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingSourceElementAdapter() {
		if (attributeMappingSourceElementItemProvider == null) {
			attributeMappingSourceElementItemProvider = new AttributeMappingSourceElementItemProvider(this);
		}

		return attributeMappingSourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.AttributeMappingExternalSourceElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingExternalSourceElementItemProvider attributeMappingExternalSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.AttributeMappingExternalSourceElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingExternalSourceElementAdapter() {
		if (attributeMappingExternalSourceElementItemProvider == null) {
			attributeMappingExternalSourceElementItemProvider = new AttributeMappingExternalSourceElementItemProvider(this);
		}

		return attributeMappingExternalSourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.AttributeMappingGlobalSourceElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingGlobalSourceElementItemProvider attributeMappingGlobalSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.AttributeMappingGlobalSourceElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingGlobalSourceElementAdapter() {
		if (attributeMappingGlobalSourceElementItemProvider == null) {
			attributeMappingGlobalSourceElementItemProvider = new AttributeMappingGlobalSourceElementItemProvider(this);
		}

		return attributeMappingGlobalSourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.CardinalityMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CardinalityMappingItemProvider cardinalityMappingItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.CardinalityMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCardinalityMappingAdapter() {
		if (cardinalityMappingItemProvider == null) {
			cardinalityMappingItemProvider = new CardinalityMappingItemProvider(this);
		}

		return cardinalityMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.CardinalityMappingSourceElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CardinalityMappingSourceElementItemProvider cardinalityMappingSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.CardinalityMappingSourceElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCardinalityMappingSourceElementAdapter() {
		if (cardinalityMappingSourceElementItemProvider == null) {
			cardinalityMappingSourceElementItemProvider = new CardinalityMappingSourceElementItemProvider(this);
		}

		return cardinalityMappingSourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.CardinalityMappingExternalSourceElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CardinalityMappingExternalSourceElementItemProvider cardinalityMappingExternalSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.CardinalityMappingExternalSourceElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCardinalityMappingExternalSourceElementAdapter() {
		if (cardinalityMappingExternalSourceElementItemProvider == null) {
			cardinalityMappingExternalSourceElementItemProvider = new CardinalityMappingExternalSourceElementItemProvider(this);
		}

		return cardinalityMappingExternalSourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.CardinalityMappingGlobalSourceElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CardinalityMappingGlobalSourceElementItemProvider cardinalityMappingGlobalSourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.CardinalityMappingGlobalSourceElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCardinalityMappingGlobalSourceElementAdapter() {
		if (cardinalityMappingGlobalSourceElementItemProvider == null) {
			cardinalityMappingGlobalSourceElementItemProvider = new CardinalityMappingGlobalSourceElementItemProvider(this);
		}

		return cardinalityMappingGlobalSourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.ReferenceTargetSelector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceTargetSelectorItemProvider referenceTargetSelectorItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.ReferenceTargetSelector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceTargetSelectorAdapter() {
		if (referenceTargetSelectorItemProvider == null) {
			referenceTargetSelectorItemProvider = new ReferenceTargetSelectorItemProvider(this);
		}

		return referenceTargetSelectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.ClassMatcher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassMatcherItemProvider classMatcherItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.ClassMatcher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassMatcherAdapter() {
		if (classMatcherItemProvider == null) {
			classMatcherItemProvider = new ClassMatcherItemProvider(this);
		}

		return classMatcherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.AttributeMatcher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMatcherItemProvider attributeMatcherItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.AttributeMatcher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMatcherAdapter() {
		if (attributeMatcherItemProvider == null) {
			attributeMatcherItemProvider = new AttributeMatcherItemProvider(this);
		}

		return attributeMatcherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.ContainerSelector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerSelectorItemProvider containerSelectorItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.ContainerSelector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerSelectorAdapter() {
		if (containerSelectorItemProvider == null) {
			containerSelectorItemProvider = new ContainerSelectorItemProvider(this);
		}

		return containerSelectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pamtram.mapping.extended.ContainerSelectorTargetAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerSelectorTargetAttributeItemProvider containerSelectorTargetAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link pamtram.mapping.extended.ContainerSelectorTargetAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerSelectorTargetAttributeAdapter() {
		if (containerSelectorTargetAttributeItemProvider == null) {
			containerSelectorTargetAttributeItemProvider = new ContainerSelectorTargetAttributeItemProvider(this);
		}

		return containerSelectorTargetAttributeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 *
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 *
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to
	 * {@link #parentAdapterFactory}. <!-- begin-user-doc --> <!-- end-user-doc
	 * -->
	 *
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 *
	 * @generated
	 */
	@Override
	public void dispose() {
		if (attributeMappingItemProvider != null) attributeMappingItemProvider.dispose();
		if (attributeMappingSourceElementItemProvider != null) attributeMappingSourceElementItemProvider.dispose();
		if (attributeMappingExternalSourceElementItemProvider != null) attributeMappingExternalSourceElementItemProvider.dispose();
		if (attributeMappingGlobalSourceElementItemProvider != null) attributeMappingGlobalSourceElementItemProvider.dispose();
		if (cardinalityMappingItemProvider != null) cardinalityMappingItemProvider.dispose();
		if (cardinalityMappingSourceElementItemProvider != null) cardinalityMappingSourceElementItemProvider.dispose();
		if (cardinalityMappingExternalSourceElementItemProvider != null) cardinalityMappingExternalSourceElementItemProvider.dispose();
		if (cardinalityMappingGlobalSourceElementItemProvider != null) cardinalityMappingGlobalSourceElementItemProvider.dispose();
		if (referenceTargetSelectorItemProvider != null) referenceTargetSelectorItemProvider.dispose();
		if (classMatcherItemProvider != null) classMatcherItemProvider.dispose();
		if (attributeMatcherItemProvider != null) attributeMatcherItemProvider.dispose();
		if (containerSelectorItemProvider != null) containerSelectorItemProvider.dispose();
		if (containerSelectorTargetAttributeItemProvider != null) containerSelectorTargetAttributeItemProvider.dispose();
	}

}
