/**
 *
 * $Id$
 */
package pamtram.condition.validation;

import org.eclipse.emf.common.util.EList;

import pamtram.condition.ComplexCondition;

/**
 * A sample validator interface for {@link pamtram.condition.And}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AndValidator {
	boolean validate();

	boolean validateCondition(EList<ComplexCondition> value);
}
