/**
 *
 * $Id$
 */
package pamtram.condition.validation;

import org.eclipse.emf.ecore.EObject;

import pamtram.condition.ComparatorEnum;

/**
 * A sample validator interface for {@link pamtram.condition.Condition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionValidator {
	boolean validate();

	boolean validateAttribute(EObject value);
	boolean validateComparator(ComparatorEnum value);
	boolean validateValue(String value);
}
