/**
 *
 * $Id$
 */
package pamtram.mapping.validation;

import org.eclipse.emf.common.util.EList;

import pamtram.mapping.AttributeValueModifierSet;
import pamtram.mapping.CalculatorMappingSourceInterface;

/**
 * A sample validator interface for {@link pamtram.mapping.CalculatorMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CalculatorMappingValidator {
	boolean validate();

	boolean validateExpression(String value);
	boolean validateVariables(EList<CalculatorMappingSourceInterface> value);
	boolean validateResultModifier(EList<AttributeValueModifierSet> value);
}
