/**
 *
 * $Id$
 */
package pamtram.mapping.validation;

import org.eclipse.emf.common.util.EList;

import pamtram.mapping.AttributeValueModifierSet;

import pamtram.metamodel.SourceSectionAttribute;

/**
 * A sample validator interface for {@link pamtram.mapping.GlobalAttribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GlobalAttributeValidator {
	boolean validate();

	boolean validateSource(SourceSectionAttribute value);
	boolean validateModifier(EList<AttributeValueModifierSet> value);
}
