/**
 *
 * $Id$
 */
package pamtram.mapping.validation;

import org.eclipse.emf.common.util.EList;

import pamtram.condition.ComplexCondition;

import pamtram.mapping.GlobalAttribute;
import pamtram.mapping.MappingHintGroupImporter;
import pamtram.mapping.MappingHintGroupType;

/**
 * A sample validator interface for {@link pamtram.mapping.Mapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappingValidator {
	boolean validate();

	boolean validateCondition(ComplexCondition value);
	boolean validateMappingHintGroups(EList<MappingHintGroupType> value);
	boolean validateImportedMappingHintGroups(EList<MappingHintGroupImporter> value);
	boolean validateGlobalVariables(EList<GlobalAttribute> value);
}
